### ISSUE TITLE
filtering for locations of major herbaria

### ISSUE THREAD

**Issue by dmcglinn** [Fireandplants/plant_gbif#14]
Hey Folks,

Another filtering question here. Erica Edwards suggests filtering out major herbaria: 

https://github.com/ejedwards/reanalysis_zanne2014/blob/master/handling_climate_data/getTminPerSpecies.py#L38

However it is not clear to me how she created the coordinate file she is using to filter out the herbaria locations: 

https://github.com/ejedwards/reanalysis_zanne2014/blob/master/handling_climate_data/allHerbaria_ADM1_badCoords.txt

She suggests that the data was accessed from this website:

http://en.wikipedia.org/wiki/List_of_herbaria

But as you can see this is just a list of names and has no coordinate information. I suppose she build the database by hand. What should we do:

1) just ignore this as it only applies to a small number of points
2) use Erica's datafile
3) build our own database of herbaria

Another related question is the issue of filtering out geopoltical centroids. This of course depends on which geopoliical shapefile you are using. I have been using an old shapefile I downloaded from GBIF back in 2011. What is considered to be the best or at least standard global geoplotical shapefile ? Here is on option: http://www.gadm.org/

**Comment by dschwilk** [comment]
I'm closing this as we decided not to do this
