### ISSUE TITLE
Use release system to isolate manuscript code

### ISSUE THREAD

**Issue by dmcglinn** [Fireandplants/plant_gbif#23]
hey @dschwilk how do you feel about using github's code release system to cleanly document the version the code is in at the time of manuscript submission and publication? It seems like that would give us more freedom to not feel obligated to distribute commits across branches for projects that are less active.

**Comment by dschwilk** [comment]
Sounds fine.  How is that different from simply tagging? It looks like it is basically a github frontend to tags (https://help.github.com/articles/creating-releases/)?

**Comment by dmcglinn** [comment]
Cool if tagging is easier then that sounds good. I haven't used tags but I have used releases hence my suggestion. I'll look into tags for myself. 
Also I just submitted a PR #24 take a look just minor changes. If you approve then I'll try to merge these into the fire branch as well.

**Comment by dschwilk** [comment]
Using releases is good by me, it also creates a tag in the process.
